OSPF:
  - interface: "GigabitEthernet3.63"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.23"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.9111"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.9222"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.7777"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.6688"
    pid: "1"
    area: "0"
  - interface: "GigabitEthernet3.6699"
    pid: "1"
    area: "0"
